-- --------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- --------------------------------------------------------------------------------
DELIMITER $$

CREATE PROCEDURE `Exec_migration_v1_vers_v2`()
BEGIN
CREATE TABLE `GRP_TYP_DIP_CORRESP` (
  `ID_GRP_TYP_DIP_CORRESP` bigint(20) NOT NULL AUTO_INCREMENT,
  `COD_GRP_TPD` varchar(10) default NULL,
  `COD_TPD_ETB` varchar(2) default NULL,
  PRIMARY KEY  (`ID_GRP_TYP_DIP_CORRESP`),
  UNIQUE KEY `COD_GRP_TPD` (`COD_GRP_TPD`,`COD_TPD_ETB`),
  KEY `FKCC87E714CA3CA59E` (`COD_GRP_TPD`)
) ENGINE=MyISAM AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;

ALTER TABLE REN1_CLES_DIPLOME_ANNU_FORM RENAME CLES_DIPLOME_ANNU_FORM;
ALTER TABLE REN1_CLES2_ANNU_FORM RENAME CLES2_ANNU_FORM;
ALTER TABLE REN1_CLES_ANNU_FORM RENAME CLES_ANNU_FORM;
ALTER TABLE REN1_DOMAINE2_ANNU_FORM RENAME DOMAINE2_ANNU_FORM;
ALTER TABLE REN1_DOMAINE_ANNU_FORM RENAME DOMAINE_ANNU_FORM;
ALTER TABLE REN1_GRP_TYP_DIP RENAME GRP_TYP_DIP;

INSERT INTO GRP_TYP_DIP_CORRESP (COD_GRP_TPD, COD_TPD_ETB) (SELECT COD_GRP_TPD, COD_TPD_ETB FROM REN1_GRP_TYP_DIP_CORRESP);

DROP TABLE REN1_GRP_TYP_DIP_CORRESP;

ALTER TABLE AUTO_LIST_PRINCIPALE MODIFY lib_nom varchar(500);
ALTER TABLE avis MODIFY commentaire varchar(500);
ALTER TABLE ind_cursus MODIFY com_cursus varchar(2000);
ALTER TABLE missing_piece MODIFY lib_miss_piece varchar(500) default NULL;
ALTER TABLE nomenclature MODIFY lib_nom varchar(500);
ALTER TABLE selection MODIFY comment_sel varchar(500);
ALTER TABLE RDV_CALENDAR MODIFY MSG_ETUDIANT varchar(5000);
ALTER TABLE RDV_CALENDAR MODIFY MSG_VALIDATION varchar(5000);
ALTER TABLE RDV_CALENDAR MODIFY MAIL longtext;