/**
* CRI - Universitï¿½ de Rennes1 - 57SI-OPIR1 - 2008
* https://subversion.univ-rennes1.fr/repos/57SI-apo-cri-webservice
* Version de la norme de dï¿½veloppement : 0.9.0
*/
package org.esupportail.opi.domain.beans.formation;


import java.io.Serializable;
import java.util.Set;

/**
 * @author cleprous
 * ClesAnnuForm generated by hbm2java
 */
public class ClesAnnuForm implements Serializable {


	/*
	 ******************* PROPERTIES ******************* */
	
	/**
	 * The serializable id. 
	 */
	private static final long serialVersionUID = -6981709942586716188L;
	
	
	/**
	 * Code mot clef.
	 */
	private String codCles;
	
	/**
	 * Code Domain (Domaine2AnnuForm).
	 */
	private String codDom;
	
	/**
	 * Temoin en service mot clef.
	 */
	private String temSveCles;
	

	/*
	 ******************* INIT ******************* */
	
	
	/**
	 * Constructor.
	 */
	public ClesAnnuForm() {
		super();
	}
	
	public ClesAnnuForm(String codCles, String codDom, String temSveCles) {
		this.codCles = codCles;
		this.codDom = codDom;
		this.temSveCles = temSveCles;
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "ClesAnnuForm#" + hashCode() + "[codDom=[" + codDom 
		+ "], codCles=[" + codCles 
		+ "], temSveCles=[" + temSveCles + "]]";
	}
	
	/** 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codCles == null) ? 0 : codCles.hashCode());
		result = prime * result + ((codDom == null) ? 0 : codDom.hashCode());
		result = prime * result
				+ ((temSveCles == null) ? 0 : temSveCles.hashCode());
		return result;
	}




	/** 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(final Object obj) {
		if (this == obj) { return true; }
		if (obj == null) { return false; }
		if (!(obj instanceof ClesAnnuForm)) { return false; }
		ClesAnnuForm other = (ClesAnnuForm) obj;
		if (codCles == null) {
			if (other.codCles != null) { return false; }
		} else if (!codCles.equals(other.codCles)) { return false; }
		if (codDom == null) {
			if (other.codDom != null) {	return false; }
		} else if (!codDom.equals(other.codDom)) { return false; }
		if (temSveCles == null) {
			if (other.temSveCles != null) {	return false; }
		} else if (!temSveCles.equals(other.temSveCles)) { return false; }
		return true;
	}


	/*
	 ******************* ACCESSORS ******************* */


	/**
	 * @return the codCles
	 */
	public String getCodCles() {
		return codCles;
	}

	/**
	 * @param codCles the codCles to set
	 */
	public void setCodCles(final String codCles) {
		this.codCles = codCles;
	}

	/**
	 * @return the codDom
	 */
	public String getCodDom() {
		return codDom;
	}

	/**
	 * @param codDom the codDom to set
	 */
	public void setCodDom(final String codDom) {
		this.codDom = codDom;
	}

	/**
	 * @return the temSveCles
	 */
	public String getTemSveCles() {
		return temSveCles;
	}

	/**
	 * @param temSveCles the temSveCles to set
	 */
	public void setTemSveCles(final String temSveCles) {
		this.temSveCles = temSveCles;
	}




}
