package org.esupportail.opi.domain.beans.formation;


// Generated 7 avr. 2009 14:43:56 by Hibernate Tools 3.2.2.GA

/**
 * DrtApoAppli generated by hbm2java
 */
public class DrtApoAppli implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3428408694575809485L;
	private String codAppli;
	private String codFonct;
	private String codTut;
	private String ctrlCmp;
	private String ctrlCge;
	private String ctrlCtn;
	private String ctrlCip;
	
	/**
	 * @return the codAppli
	 */
	public String getCodAppli() {
		return codAppli;
	}
	/**
	 * @param codAppli the codAppli to set
	 */
	public void setCodAppli(String codAppli) {
		this.codAppli = codAppli;
	}
	/**
	 * @return the codFonct
	 */
	public String getCodFonct() {
		return codFonct;
	}
	/**
	 * @param codFonct the codFonct to set
	 */
	public void setCodFonct(String codFonct) {
		this.codFonct = codFonct;
	}
	/**
	 * @return the codTut
	 */
	public String getCodTut() {
		return codTut;
	}
	/**
	 * @param codTut the codTut to set
	 */
	public void setCodTut(String codTut) {
		this.codTut = codTut;
	}
	/**
	 * @return the ctrlCmp
	 */
	public String getCtrlCmp() {
		return ctrlCmp;
	}
	/**
	 * @param ctrlCmp the ctrlCmp to set
	 */
	public void setCtrlCmp(String ctrlCmp) {
		this.ctrlCmp = ctrlCmp;
	}
	/**
	 * @return the ctrlCge
	 */
	public String getCtrlCge() {
		return ctrlCge;
	}
	/**
	 * @param ctrlCge the ctrlCge to set
	 */
	public void setCtrlCge(String ctrlCge) {
		this.ctrlCge = ctrlCge;
	}
	/**
	 * @return the ctrlCtn
	 */
	public String getCtrlCtn() {
		return ctrlCtn;
	}
	/**
	 * @param ctrlCtn the ctrlCtn to set
	 */
	public void setCtrlCtn(String ctrlCtn) {
		this.ctrlCtn = ctrlCtn;
	}
	/**
	 * @return the ctrlCip
	 */
	public String getCtrlCip() {
		return ctrlCip;
	}
	/**
	 * @param ctrlCip the ctrlCip to set
	 */
	public void setCtrlCip(String ctrlCip) {
		this.ctrlCip = ctrlCip;
	}

	

	
}
